### ISSUE TITLE
Why use the pool(x) - x

### ISSUE THREAD

**Issue by FlyEgle** [sail-sg/poolformer#1]
I have a quesition for use the pool(x) - x 

I give the answer is : pooling is used for smooth x, '-' mean model ignore the same value with the pool size and focus the neightbor wihch small or bigger than smooth x. Reinforcement the relation for the 8-neighboor.

So this pooling is the local-relation, than use the conv mlp  mixer to exchange the information for gloabl.

Is that reason? Thank for you replay

**Comment by yuweihao** [comment]
Hi @FlyEgle ,

As shown in the paper, since the MetaFormer block already has a residual connection, subtraction of the input
itself is added in Equation (4).

**Comment by wsy-yjys** [comment]
@yuweihao Hi, have you tried pool(x)+x or pool(x)?

**Comment by yuweihao** [comment]
Hi @wsy-yjys , I tried `pool(x)` and `pool(x) - x`. I remember `pool(x) -x ` is better than `poo(x)` by about 0.2 or 0.3 accuracy (the number is a bit blurry). I have not tried `pool(x) + x`.

**Comment by wsy-yjys** [comment]
@yuweihao  Thank you for your reply.  I am very curious how did you come up with the idea of  `pool(x) - x` at that time?

**Comment by yuweihao** [comment]
@yuweihao , from the perspective of image processing, `pool(x) is Mean Filter while `pool(x) -x ` is Laplacian Filter. At that time, I wanted to specify the token mixers as extremely sample operators, so I tried these simple filters without any learnable parameters.
