### ISSUE TITLE
when will segmentation configs out?

### ISSUE THREAD

**Issue by ShihuaHuang95** [sail-sg/poolformer#12]
Many thanks for your excellent work. 
   I have tried to used the pretrained  PoolFormer_S12 with SemanticFPN configs from MMSegmentation with default setting (16w iterations). But, the model just achieved 36+ mIoU (Single-scale testing) over ADE20k, which is much lower than the result (37.2) in the main paper. 
  Could you please share the segmentation configs?

**Comment by yuweihao** [comment]
Hi @ShihuaHuang95 ,

Thank you very much for your attention to our work. I will push myself to arrange and release the configs and models in about 3 days, no more than a week. Actually, the segmentation configs of PoolFormer just simply follow those of PVT although PVT's hyper-parameters may not be optimal to PoolFormer.

**Comment by yuweihao** [comment]
Hi @ShihuaHuang95 ,

The segmentation configs are released [here](https://github.com/sail-sg/poolformer/tree/main/segmentation).

**Comment by ShihuaHuang95** [comment]
Noted with thanks!
