### ISSUE TITLE
It is hard to reproduce the ADE20k result with PoolFormer S12

### ISSUE THREAD

**Issue by ShihuaHuang95** [sail-sg/poolformer#19]
Hi, I have tried to reproduce the ADE20k with S12 which is 37.2 for three times. And the results are 36.86, 36.87, and 36.92. I have not modified any default settings.

**Comment by yuweihao** [comment]
Hi @ShihuaHuang95 , do you use apex and the training code in the [detection folder](https://github.com/sail-sg/poolformer/tree/main/detection)? I simply follow the training code from [PVT detection](https://github.com/whai362/PVT/tree/v2/detection). You may install apex and use the training code to try again.

**Comment by ShihuaHuang95** [comment]
@yuweihao Many thanks for your kind help and best wishes. 
 The detection is fine and I am worried about the segmentation over ADE20K.

**Comment by yuweihao** [comment]
Hi, @ShihuaHuang95 , sorry, it is a typo, both detection and segmentation follow training code from PVT. I have fixed the typo above.
