### ISSUE TITLE
Addition of the Organization on HuggingFace Transformers

### ISSUE THREAD

**Issue by heytanay** [sail-sg/poolformer#26]
Hello PoolFormer team!

I have been working on porting the implementation of PoolFormer to HuggingFace Transformers library (you can see my PR [here](https://github.com/huggingface/transformers/pull/15250)) and I was wondering if I can go ahead and add Sea AI labs as an organization to the HuggingFace models hub.

This will allow all model checkpoints to be uploaded onto the hub as well as model cards, etc.

Kind regards,
Tanay Mehta

**Comment by yuweihao** [comment]
Hi @heytanay , 

Sure. Many thanks for your contribution to porting the implementation of PoolFormer to HuggingFace Transformers. I have just created the [Sea AI Lab organization](https://huggingface.co/sail) on the HuggingFace model hub. Could I know what is your HuggingFace account?

**Comment by heytanay** [comment]
Hi @yuweihao, thanks for creating an organization!

My Hugging Face account is: https://huggingface.co/heytanay

I have also requested to join the organization!

Thanks and regards,
Tanay Mehta

**Comment by yuweihao** [comment]
Many thanks :)

**Comment by heytanay** [comment]
Little change, I have closed the last PR and opened a new one [here](https://github.com/huggingface/transformers/pull/15531)

Sorry for any inconvenience.

**Comment by wh-yu** [comment]
Note with thanks :)

**Comment by yuweihao** [comment]
Noted with thanks :)

**Comment by heytanay** [comment]
Hi @yuweihao,
The PoolFormer model has been added to 🤗 transformers (PR was merged yesterday)
You can view the docs here: https://huggingface.co/docs/transformers/master/en/model_doc/poolformer

I was also wondering if you could write the model cards? (for all the models: https://huggingface.co/sail)

Thank you!

**Comment by yuweihao** [comment]
Hi @heytanay,

Many thanks for your contribution. 

I will write the model cards in a few days.

Thank you again :)
