### ISSUE TITLE
when will detection configs out?

### ISSUE THREAD

**Issue by jinfagang** [sail-sg/poolformer#3]
when will detection configs out?

**Comment by yuweihao** [comment]
Hi @jinfagang , 

Thank you for your attention. We will release it soon. We do not particularly tune the hyper-parameters for detection. You can just use common configs in the mmdetection package.  The model code for detection is also in models/poolformer.py.

**Comment by jinfagang** [comment]
@yuweihao any timeline for this?

**Comment by yuweihao** [comment]
Hi @jinfagang ,

Thank you for your attention. I will release it in a week.

**Comment by yuweihao** [comment]
Hi @jinfagang ,

Sorry that I have other things to do these days. Give me one day to arrange the detection code and configs. I will release them tomorrow.

**Comment by jinfagang** [comment]
@yuweihao that's nice, take your time.

**Comment by yuweihao** [comment]
Hi @jinfagang ,

The detection configs are released [here](https://github.com/sail-sg/poolformer/tree/main/detection).

**Comment by jinfagang** [comment]
@yuweihao thank u. BTW, have u tested speed between poolformer-s series and pvtv2 series model? how's the speed in terms of their smallest one? For instance, poolformer-s12 and pvtv2-b0?

**Comment by yuweihao** [comment]
Hi @jinfagang ,

I have not compared the speed between PoolFormer and PVT-v2.  The "FLOPs" in PVT-v2 paper actually mean MACs. You can compare the MACs between Table 2 in the MetaFormer paper and Table 2 in the PVT-v2 paper, both of which show the MACs of the two models under the input of 224 * 224. This may roughly refelt their speed.

**Comment by jinfagang** [comment]
@yuweihao both flops and macs hardly gives users a very straight sense of speed. What's the inference speed of poolformer-retinanet on a normal GPU such as 3090 or v100?

**Comment by yuweihao** [comment]
Hi @jinfagang , currently I do not have GPU 3090 or V100 to use, could you please help test PoolFormer on these GPUs? Many Thanks.
