### ISSUE TITLE
Invitation of making PR for OpenMMLab / MMSegmentation.

### ISSUE THREAD

**Issue by MengzhangLI** [sail-sg/poolformer#30]
Hi, first congrats for acceptance of CVPR'2022. This work deserves because it is very great. 

I am a member of OpenMMLab and mainly work for developing MMSegmentation. I think if it supported officially, many more people would use it for benchmark, which would promote research in computer vision area.

Would you like to make PR for openmmlab? We could discuss together to refactor your code and use our own GPUs to train & re-implement.

I think it is pretty cool because it would make more reseachers and community members use this excellent work! Here is our re-implementing work: [ConvNeXt](https://github.com/open-mmlab/mmsegmentation/tree/master/configs/convnext). 

We do hope PoolFormer could also be added as backbones in our codebase so that many researchers could use directly it for downstream tasks.

Looking forward to your reply!

Best,

**Comment by yuweihao** [comment]
Hi @MengzhangLI ,

Thanks for your attention and invitation. MMSegmentation is the wonderful codebase I base on to implement PoolFormer for semantic segmentation tasks. Thank you and other MMSegmentation contributors. I am glad to make PR of PoolFormer to MMSegmentation. I will do it in a few days.

Thank you :)

**Comment by MengzhangLI** [comment]
Well, that's pretty cool! ;)

I think we could first support PoolFormer backbone into MMClassification, then downstream MMDetection and MMSegmentation could utilize this backbone. Here is related [Chinese article in Zhihu](https://zhuanlan.zhihu.com/p/436865195).

Here are:

(1) Reference about ConvNext.
In ConvNext, we refactored its original code and made [pr in mmclassification](https://github.com/open-mmlab/mmclassification/pull/670). I think PoolFormer could follow this procedure, i.e., you just make a pr in MMClassfication, and we would review it to refactor it into our usual code style. 

Here are our current ConvNext in [mmclassification](https://github.com/open-mmlab/mmclassification/tree/master/configs/convnext) and downstream [MMSegmentation PR](https://github.com/open-mmlab/mmsegmentation/pull/1216), which would be merged in this week.

(2) Making a pull request.
Usefule links: [Contributing to OpenMMLab](https://github.com/open-mmlab/mmcv/blob/master/CONTRIBUTING.md) and [Chinese article from zhihu](https://zhuanlan.zhihu.com/p/339080395).


For PoolFormer, please refer to  [PR about supporting ConvNext in MMClassification](https://github.com/open-mmlab/mmclassification/pull/670). Refactoring is a little bit laborious but that would make users more convenient after this treatment. We would respond to your pr quickly!

We need to first ensure current models (such as in ImageNet and ADE20K) could get same results in this PR, aka, aligning inference metric.

After that, we would train many models (for example, PoolFormer-M48 + Semantic FPN) to re-implement paper results. That would be implemented on our computation resources. 

If you have any problems about usage or pr of MMSegmentation and MMClassification, feel free to contact us. Let's work together to provide PoolFormer as a benchmark for community!

Best,

**Comment by yuweihao** [comment]
Many thanks for the information.

**Comment by MengzhangLI** [comment]
Hi weihao, how are you these days? Wish you all the best about ECCV'2022.

I have just finished PR about [K-Net](https://github.com/open-mmlab/mmsegmentation/tree/master/configs/knet), this month is more time available. 

When you have time to make a pr for PoolFormer, we could create a wechat group to work together. So feel free to make pr or contact us for any problems.

Best,

**Comment by yuweihao** [comment]
Hi @MengzhangLI ,

Thank you. Sorry that I am busy these days. I will start to work on this PR tomorrow. I will contact you by email and WeChat. Thanks :)
