### ISSUE TITLE
cvpr2022 call for demos

### ISSUE THREAD

**Issue by AK391** [sail-sg/poolformer#31]
Hi, there is a call for demos this year for cvpr 2022

https://cvpr2022.thecvf.com/call-demos

where a demo can be added to the Hugging Face organization here: https://huggingface.co/cvpr

would you be interested in submitting a demo for this?

**Comment by yuweihao** [comment]
Hi @AK391 ,

Thanks for the information. Currently, we do not have a plan to prepare submissions of demos for the CVPR Demo Track.

Thank you again for your contribution in making an interesting [online demo](https://huggingface.co/spaces/akhaliq/poolformer) on Huggingface Spaces for PoolFormer :)
