### ISSUE TITLE
Inquiry about the Hybrid design

### ISSUE THREAD

**Issue by AbdelrahmanShakerYousef** [sail-sg/poolformer#32]
Hello, thank you for sharing the code of the paper.

Could you please release the code of the hybrid design?

Also, I have a question please about the hybrid design in Table. 6. Did you replace the whole pooling stage with attention or SpatialFC stage ? or just replace the last block of each stage?

Thank you.

**Comment by yuweihao** [comment]
Hi @AbdelrahmanShakerYousef ,

Thanks for your attention. 

Sorry that currently, I need to prepare for my final exams. I will release the code and trained models of the hybrid design before 1 May. We replace the whole pooling stage with the attention or SpatialFC stage. Remember to add position embedding before the first attention stage. For hybrid design, the norm is set as Layer Norm and the batch size as 1024.

**Comment by yuweihao** [comment]
Hi @AbdelrahmanShakerYousef ,

I have completed the release of [code](https://github.com/sail-sg/poolformer/blob/main/models/metaformer.py) and trained models of the hybrid design before 1 May (Anywhere on Earth Time Zone haha).

Thanks for your attention :)
