### ISSUE TITLE
why use use_layer_scale

### ISSUE THREAD

**Issue by rtfgithub** [sail-sg/poolformer#35]
thanks for your great contribution! 
in the  implement for poolformerblock ,there is a layer_scale after token_mixer. What is the impact of this operation?

**Comment by yuweihao** [comment]
Hi @rtfgithub ,

Like stochastic depth, LayerScale can help train the models. For more details, please refer to the following that proposes this operator.

[Going deeper with Image Transformers](https://arxiv.org/abs/2103.17239)

**Comment by rtfgithub** [comment]
thanks for your reply！I'd like to ask you another question.
As mentioned in your paper, the Training strategy of poolformer follow DEIT method. Did you  add the distillation token to model and use the distillation method with Hard-label distillation loss?

**Comment by yuweihao** [comment]
Hi @rtfgithub ,

We follow the training hyper-parameters of DeiT but we don't add distillation methods.

**Comment by rtfgithub** [comment]
thank u for your reply!Good luck！

**Comment by yuweihao** [comment]
You are welcome :)
