### ISSUE TITLE
How to achieve the grad-CAM visualization? 

### ISSUE THREAD

**Issue by DoranLyong** [sail-sg/poolformer#36]
Thanks for your awesome work and for sharing them all.

I found out that the pictures in [the supplement paper](https://openaccess.thecvf.com/content/CVPR2022/supplemental/Yu_MetaFormer_Is_Actually_CVPR_2022_supplemental.pdf) are beautiful, and I want to follow this. 

Could you share the code for this? or can tell me how to achieve the grad-CAM activation map?

**Comment by yuweihao** [comment]
Hi @DoranLyong , I use the repo [pytorch-grad-cam](https://github.com/jacobgil/pytorch-grad-cam) for visualization. I just upload the code that I use, please see [misc/cam_image.py](https://github.com/sail-sg/poolformer/blob/main/misc/cam_image.py). 
```
python3 cam_iamge.py --model poolformer_s12
```

**Comment by DoranLyong** [comment]
Yeah~ I did :)  Thank you very much~ 

<img src="https://user-images.githubusercontent.com/13333380/173169948-6ccf9bf6-c644-4398-aed7-461cad3a73bd.png" width=480>

**Comment by yuweihao** [comment]
You are welcome :)
