### ISSUE TITLE
Aboutu the results graph

### ISSUE THREAD

**Issue by paidaxing485** [sail-sg/poolformer#38]
Hello, can you tell me hows to get the results graph？

**Comment by yuweihao** [comment]
Hi @paidaxing485 ,

Thanks for your attention. Do you mean the figure 3 in the paper? We drew the figure using the python package matplotlib.

**Comment by yuweihao** [comment]
@paidaxing485 ,

To get the quantitative results, please refer to [this](https://github.com/sail-sg/poolformer/tree/main/segmentation#evaluation). To visualize the results, please refer to this [code](https://github.com/open-mmlab/mmsegmentation/blob/master/demo/image_demo.py) from mmsegmentation.
