### ISSUE TITLE
About MLN（Modified Layer Normalization）

### ISSUE THREAD

**Issue by youngtboy** [sail-sg/poolformer#40]
This paper provides new perspectives about Transformer block, but I have some questions about one of the details.
As far as I know, the LayerNorm officially provided by Pytorch implements the same function as the MLN, which computes the
mean and variance along token and channel dimensions. So where is the improvement?
![image](https://user-images.githubusercontent.com/66102178/191280570-ac885e34-3a22-41c4-901d-72d3e3dd099e.png)
**The official example :**
#Image Example
N, C, H, W = 20, 5, 10, 10
input = torch.randn(N, C, H, W)
#Normalize over the last three dimensions (i.e. the channel and spatial dimensions)
#as shown in the image below
layer_norm = nn.LayerNorm([C, H, W])
output = layer_norm(input)

**Comment by yuweihao** [comment]
Hi @youngtboy ,

Thanks for your attention. Please refer to this issue #9 .

**Comment by youngtboy** [comment]
> Hi @youngtboy ,
> 
> Thanks for your attention. Please refer to this issue #9 .

Thanks for your explanation!

**Comment by yuweihao** [comment]
Duplicate of #9
