### ISSUE TITLE
s12 model Reproduction experiment

### ISSUE THREAD

**Issue by starsky68** [sail-sg/poolformer#42]
Using the s12 model, only the four card batch size is 240 for a single card, and the acc top1 is 76 in the end. If there are no eight cards, how can the acc reach 80，Other parameter defaults.  --Apex amp can greatly affect the accuracy in addition to fast training.

**Comment by yuweihao** [comment]
Hi @starsky68 ,

Thanks for your attention. Please refer to the [train.py](https://github.com/sail-sg/metaformer/blob/main/train.py) file in [metaformer](https://github.com/sail-sg/metaformer) repo where I add `--grad-accum-steps` so that you can set larger batch size.
