### ISSUE TITLE
How to check the number of parameters of both object detection and instance segmentation

### ISSUE THREAD

**Issue by DoranLyong** [sail-sg/poolformer#48]
Thanks for your nice work. 
I'm employing your baseline for my work. 

I have a question about how to get the number of parameters for object detection and instance segmentation in your paper. 
I checked how to do in image classification case  in the 'misc', but I'm not familiar with mmlab's library. 
Could you please how to do that?
![Screenshot from 2023-02-07 19-57-27](https://user-images.githubusercontent.com/13333380/217226406-a633e2ea-bd7c-4127-90b4-560932be8270.png)

**Comment by yuweihao** [comment]
Hi @DoranLyong , a simple method is to count the number of parameters stored in `.pth` file. Another method is to utilize tools offered by mmdet or mmseg like [this](https://github.com/open-mmlab/mmdetection/blob/master/tools/analysis_tools/get_flops.py).

**Comment by DoranLyong** [comment]
I've always appreciated your fast response! 
I solved it owing to your tips.

* reference [link](https://mmsegmentation.readthedocs.io/en/latest/useful_tools.html#get-the-flops-and-params-experimental) for mmsegmentation
* usage: 
```
python tools/get_flops.py configs/sem_fpn/PoolFormer/fpn_poolformer_s12_ade20k_40k.py --shape 512
```
![Screenshot from 2023-02-09 12-02-50](https://user-images.githubusercontent.com/13333380/217707194-ccac47ac-4b56-46b0-80d8-b7deff8acfae.png)
