### ISSUE TITLE
Checkpoints of the Ablation study

### ISSUE THREAD

**Issue by chuong98** [sail-sg/poolformer#5]
Hi, thanks for your amazing work.
I am reading the Tab 6, and I am surprised because the method is so simple and very effective, especially when the Pooling is replaced with Identity Mapping. Top1 74.3 on ImageNet-1k with only Conv1x1 and Norm layer. I am thrilled... 
Can you release this checkpoint so that we can verify.  Thanks again.
![image](https://user-images.githubusercontent.com/15174756/143518228-92ae8ec8-074f-4b5d-9475-caed79bd8a6a.png)

**Comment by chuong98** [comment]
Is one of the following implementation correct for the Identity Case ?:
Case A:
```python
  def forward(self,x):
            x = x + self.drop_path(self.norm1(x))
            return x + self.drop_path(self.mlp(self.norm2(x)))
```
Case B:
```python
def forward(self,x):
           x + self.drop_path(self.mlp(self.norm2(x)))
```

**Comment by yuweihao** [comment]
Hi @chuong98 ,

There is a simple way to implement it. You just need to modify `self.token_mixer = Pooling(pool_size=pool_size)` to `self.token_mixer = nn.Identity()`.

The checkpoint is shown in:
[poolformer_id_s12.pth.tar](https://drive.google.com/file/d/1kT4uWWhEesjosKlwXv6obLBoOm4_gACO/view?usp=sharing)

**Comment by chuong98** [comment]
Wonderful! I evaluated the ckpt ang got 74.336. 
![image](https://user-images.githubusercontent.com/15174756/143664687-87cb651d-7a16-469a-b21d-e73c7bb2f750.png)
But when I inspect the speed, the sp_12 is about 3x slower than ResNet 18. I inspect the model, and when replace the GroupNorm with BatchNorm, the inference time reduces 1/2. 
Would you mind release the ckpts of Using BatchNorm/and/or ReLU ? Thank you so much.

**Comment by chuong98** [comment]
Regarding to using Identity instead of pooling, I can't explain why it works. Because pooling is the only mechanism the network learns about the spatial information. Now we even drop the pooling. Can you share your thoughts?

**Comment by yuweihao** [comment]
Hi @chuong98 ,

The checkpoints of BatchNorm or ReLU are in [poolformer_bn_s12.pth.tar](https://drive.google.com/file/d/1c0TIlfZgumXcKEQxNrnzpwIkLZ0UoH2P/view?usp=sharing), [poolformer_relu_s12.pth.tar](https://drive.google.com/file/d/106uyS3JXGlwLDIVyI7n1GtHcdAu5Na7W/view?usp=sharing).

The reason why the identity token mixer still works is that sometimes local information is enough to predict. For example, for humans, our faces are largely different from other animals.
