### ISSUE TITLE
你好，我有一些结构的问题

### ISSUE THREAD

**Issue by asfx0412** [sail-sg/poolformer#55]
KeyError: "RetinaNet: 'poolformer_s12 is not in the models registry'"

**Comment by linloong** [comment]
Hello, may I ask if you have solved this problem later. I'm getting the same error when I run it.
Thank you!

**Comment by asfx0412** [comment]
Hello, I have resolved this issue. One of the modules is a private library that needs to be downloaded from its git. It cannot be downloaded directly from the global library, so there will be no errors

**Comment by linloong** [comment]
Thanks for your reply!
